// API
export const API_REQUEST = 'API_REQUEST';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const API_ERROR = 'API_ERROR';

// QUESTIONS
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTION_DETAILS = 'FETCH_QUESTION_DETAILS';

export const ADD_QUESTION = 'ADD_QUESTION';
export const RESET_ADD_QUESTION = 'RESET_ADD_QUESTION';

export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS';
export const UPDATE_QUESTION_DETAILS = 'UPDATE_QUESTION_DETAILS';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';

// VOTE
export const SAVE_VOTE = 'SAVE_VOTE';
export const UPDATE_VOTE = 'UPDATE_VOTE';

